[package]
name = "project_euler"
version = "0.1.0"
authors = ["Ryan Brewster <ryanpbrewster@gmail.com>"]
edition = "2018"

[dependencies]
num = "0.2"
lazy_static = "1.4"
petgraph = "0.5"
rand = "0.7"
rand_pcg = "0.2"
rayon = "1.3"
assert_approx_eq = "1.1"
